# Generated by Django 6.1.1 on 2026-09-18 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_collections/%Y/%m/', verbose_name='Fotografía de la Planta')),
                ('common_name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre Común')),
                ('scientific_name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre Científico')),
                ('family', models.CharField(default='Desconocida', max_length=150, verbose_name='Familia Botánica')),
                ('category', models.CharField(db_index=True, default='General', max_length=100, verbose_name='Categoría')),
                ('origin', models.CharField(blank=True, default='', max_length=200, verbose_name='Origen Geográfico')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción Botánica')),
                ('light_requirement', models.CharField(blank=True, default='', max_length=250, verbose_name='Requerimiento de Luz')),
                ('watering_frequency', models.CharField(blank=True, default='', max_length=250, verbose_name='Frecuencia de Riego')),
                ('temperature_range', models.CharField(blank=True, default='', max_length=100, verbose_name='Rango de Temperatura')),
                ('humidity_requirement', models.CharField(blank=True, default='', max_length=100, verbose_name='Humedad Ambiental')),
                ('difficulty', models.CharField(default='Moderado', max_length=50, verbose_name='Dificultad de Cuidado')),
                ('toxicity_pets', models.BooleanField(default=False, verbose_name='Tóxica para Mascotas (Perros/Gatos)')),
                ('toxicity_humans', models.BooleanField(default=False, verbose_name='Tóxica para Humanos / Niños')),
                ('toxicity_details', models.TextField(blank=True, default='', verbose_name='Detalles de Toxicidad')),
                ('fun_facts', models.TextField(blank=True, default='', verbose_name='Curiosidades e Historia')),
                ('confidence', models.FloatField(default=0.95, verbose_name='Nivel de Confianza IA (0.0 - 1.0)')),
                ('user_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Campo del Usuario')),
                ('location_found', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Hallazgo / Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Colección')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_plants', to=settings.AUTH_USER_MODEL, verbose_name='Coleccionista')),
            ],
            options={
                'verbose_name': 'Planta Coleccionada',
                'verbose_name_plural': 'Álbum de Plantas Coleccionadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
