# Generated by Django 5.0.14 on 2026-09-01 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_initial'),
        ('diagnosis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Consulta Agronómica', max_length=200, verbose_name='Título de la Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='crops.crop', verbose_name='Cultivo en Consulta')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='diagnosis.diagnosis', verbose_name='Diagnóstico Asociado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Chat IA',
                'verbose_name_plural': 'Sesiones de Chat IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario / Agricultor'), ('assistant', 'Asistente Botánico IA'), ('system', 'Instrucción del Sistema')], max_length=20, verbose_name='Emisor')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('suggested_actions', models.JSONField(blank=True, default=dict, verbose_name='Acciones Sugeridas (Tratamiento / Calendario)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['sent_at'],
            },
        ),
    ]
