# Generated by Django 5.0.14 on 2026-09-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Lote Tomates 1', max_length=150, verbose_name='Nombre / Identificador')),
                ('species', models.CharField(help_text='Ej: Tomate, Café, Papa, Maíz, Manzano', max_length=100, verbose_name='Especie')),
                ('variety', models.CharField(blank=True, help_text='Ej: Canchan, Caturra, Roma', max_length=100, verbose_name='Variedad')),
                ('planting_date', models.DateField(verbose_name='Fecha de Siembra')),
                ('estimated_harvest_date', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Cosecha')),
                ('status', models.CharField(choices=[('growing', 'En Crecimiento'), ('healthy', 'Saludable'), ('alert', 'En Riesgo / Enfermo'), ('harvesting', 'En Cosecha'), ('harvested', 'Cosechado'), ('archived', 'Archivado')], default='growing', max_length=20, verbose_name='Estado del Cultivo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Foto del Cultivo')),
                ('water_requirement', models.CharField(default='Cada 2 días', max_length=100, verbose_name='Frecuencia de Riego')),
                ('sunlight_requirement', models.CharField(default='Pleno Sol', max_length=100, verbose_name='Exposición Solar')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Parcela')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación / Sector')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('area_hectares', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Área (Hectáreas)')),
                ('soil_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Suelo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas u Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Excelente / Saludable'), ('good', 'Bueno / Normal'), ('warning', 'Alerta / Síntomas Leves'), ('critical', 'Crítico / Plaga Avanzada'), ('recovered', 'Recuperado')], default='good', max_length=20, verbose_name='Estado')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Entrada')),
                ('observations', models.TextField(verbose_name='Observaciones de la Evolución')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='status_logs/', verbose_name='Foto de Estado')),
                ('logged_at', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácora de Estado',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='CareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('watering', 'Riego'), ('fertilization', 'Fertilización'), ('pruning', 'Poda'), ('fumigation', 'Fumigación / Tratamiento'), ('harvest', 'Cosecha'), ('monitoring', 'Monitoreo / Inspección'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Cuidado')),
                ('title', models.CharField(max_length=150, verbose_name='Título / Acción')),
                ('event_date', models.DateTimeField(verbose_name='Fecha y Hora del Evento')),
                ('product_used', models.CharField(blank=True, max_length=150, verbose_name='Producto / Abono Utilizado')),
                ('amount', models.CharField(blank=True, max_length=100, verbose_name='Dosis / Cantidad')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_events', to='crops.crop', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Evento de Cuidado',
                'verbose_name_plural': 'Historial de Cuidados',
                'ordering': ['-event_date'],
            },
        ),
    ]
