# Generated by Django 5.0.14 on 2026-09-01 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='crop',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops.plot', verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='crops.crop', verbose_name='Cultivo'),
        ),
    ]
