# Generated by Django 5.0.14 on 2026-09-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnoses/%Y/%m/', verbose_name='Foto de la Hoja / Síntoma')),
                ('disease_common_name', models.CharField(max_length=200, verbose_name='Nombre Común de la Enfermedad')),
                ('disease_scientific_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Científico / Patógeno')),
                ('confidence', models.FloatField(help_text='Porcentaje de certeza de la IA (0-100)', verbose_name='Nivel de Certeza (%)')),
                ('severity', models.CharField(default='Moderada', max_length=50, verbose_name='Severidad Estimada')),
                ('is_healthy', models.BooleanField(default=False, verbose_name='Planta Saludable')),
                ('symptoms', models.TextField(blank=True, verbose_name='Síntomas Identificados')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Plan de Acción Recomendado')),
                ('top_predictions', models.JSONField(blank=True, default=list, verbose_name='Top 3 Predicciones')),
                ('user_feedback', models.CharField(choices=[('confirmed', 'Confirmado por usuario'), ('doubtful', 'Dudoso'), ('rejected', 'Rechazado'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Confirmación del Agricultor')),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Diagnóstico')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='crops.crop', verbose_name='Cultivo Afectado')),
            ],
            options={
                'verbose_name': 'Diagnóstico Fitosanitario',
                'verbose_name_plural': 'Historial de Diagnósticos',
                'ordering': ['-diagnosed_at'],
            },
        ),
    ]
