# Generated by Django 5.0.14 on 2026-09-01 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('watering', 'Recordatorio de Riego'), ('fertilization', 'Aplicación de Fertilizante'), ('disease_check', 'Revisión de Síntomas / Fitosanitaria'), ('pruning', 'Poda'), ('fumigation', 'Fumigación de Control'), ('custom', 'Alerta Personalizada')], default='watering', max_length=20, verbose_name='Tipo de Alerta')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Alerta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Instrucciones')),
                ('scheduled_for', models.DateTimeField(verbose_name='Fecha y Hora Programada')),
                ('recurrence_days', models.PositiveIntegerField(default=0, help_text='0 para alerta única', verbose_name='Repetir cada (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Disparada')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='crops.crop', verbose_name='Cultivo Destino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alerta de Cuidado',
                'verbose_name_plural': 'Alertas de Cuidado',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('warning', 'Alerta Fitosanitaria'), ('info', 'Información'), ('success', 'Éxito')], default='reminder', max_length=20, verbose_name='Tipo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Enlace de Destino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reports.alert', verbose_name='Alerta Origen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
